### PR TITLE
add guide to dungeon hub races

### PR DESCRIPTION
**Pull request by SeRaid743**
data for dungeon hub races - needed for another pr

### CODE REVIEW

**Review by CalMWolfs — APPROVED** [review]

**Review by Thunderblade73 — CHANGES_REQUESTED** [review]
This json is not future prove. Since the races have different states they are in and adding in stuff later on gets comlicated. So make it instead of Map<String,ParkourJson> to Map<String,Map<String,ParkourJson>> and set the second layer to "Nothing, No return"

**Comment by CalMWolfs** [comment]
> This json is not future prove. Since the races have different states they are in and adding in stuff later on gets comlicated. So make it instead of Map<String,ParkourJson> to Map<String,Map<String,ParkourJson>> and set the second layer to "Nothing, No return"

While this is true, I dont belive waypoints are useful for any of the races other than the no-return, nothing category so in my opinion it is fine as is

**Comment by qtlunya** [comment]
How are they not useful? Sure, they're technically not necessary to do because you can get the talismans without them, but what if someone wants to complete all the objectives or something?

**Comment by ThatGravyBoat** [comment]
> This json is not future prove. Since the races have different states they are in and adding in stuff later on gets comlicated. So make it instead of Map<String,ParkourJson> to Map<String,Map<String,ParkourJson>> and set the second layer to "Nothing, No return"

There is no reason to do this, overcomplicating the data structure for a theoretical future feature that will likely never happen does not make any sense. Either way in the future if such a feature will be made the names can be suffixed or prefixed for example `no_pearls:giant_mushroom` and `no_abilities:precursor_ruins`

**Comment by qtlunya** [comment]
How exactly is it "overcomplicating" to make a perfectly logical data structure? Your argument is ridiculous.

**Comment by Thunderblade73** [comment]
We have so many scuffed jsons. I don't want to handle another one. Also there is a defined future where this happens, since the feature requested all not 4 to complete the talisman.

**Comment by SeRaid743** [comment]
fixed :3

**Comment by Thunderblade73** [comment]
Could you separate the part "nothing" and "no_return" with a different symbol. E.g ":". Makes it easier to work with

**Comment by SeRaid743** [comment]
done <3

**Review by Thunderblade73 — APPROVED** [review]

**Comment by hannibal002** [comment]
Can we please start with a template that contains the structure for all possible races? Then just fill in the currently existing data.

**Comment by CalMWolfs** [comment]
> Can we please start with a template that contains the structure for all possible races? Then just fill in the currently existing data.

The current format allows for it to work fine with new ones already, and I believe that adding these extra fields will just add clutter that is not needed

**Comment by SeRaid743** [comment]
> Can we please start with a template that contains the structure for all possible races? Then just fill in the currently existing data.

done i think :3

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
