### PR TITLE
Add Missing /gfs items

### PR DESCRIPTION
**Pull request by walkerselby**
I am sure there are more missing. I will check at some point, but not at the moment.

### CODE REVIEW

**Comment by j10a1n15** [comment]
Enchanted Hardstone is also missing.
Feel free to add it, since my pr (#52 ) is already half redundant

**Comment by walkerselby** [comment]
> Enchanted Hardstone is also missing. Feel free to add it, since my pr (#52 ) is already half redundant

You PRed that already, let me just remove from mine.

**Comment by j10a1n15** [comment]
I also feel like compost bundles are missing, since the normal compost was missing

**Comment by walkerselby** [comment]
> I also feel like compost bundles are missing, since the normal compost was missing

Turns out Compost Bundles are just not in sacks

**Comment by j10a1n15** [comment]
> Turns out Compost Bundles are just not in sacks

Wtf i couldve sworn they once were lol

**Comment by jani270** [comment]
> > Turns out Compost Bundles are just not in sacks
> 
> Wtf i couldve sworn they once were lol

UUID moment

**Pull request merged**
