### PR TITLE
Add Enchanted Ancient Claw to quick craftable items

### PR DESCRIPTION
**Pull request by FluxCapacitor2**

### CODE REVIEW

**Comment by martimavocado** [comment]
i might be alone on this, but i would rather not quick craft them since they're not npcable, and to regular profiles, selling regular claws is much better money

**Comment by FluxCapacitor2** [comment]
> i might be alone on this, but i would rather not quick craft them since they're not npcable, and to regular profiles, selling regular claws is much better money

Oh, you have a good point! I never thought of that.

**Comment by hannibal002** [comment]
Closing for inactivity and not apparently needed

**Comment by alexiayaa** [comment]
Yeah, and you might also accidentally craft some when you meant to use normal ones and especially on ironman that's annoying.

**Pull request closed without merging**
