### PR TITLE
Add pet leveling info

### PR DESCRIPTION
**Pull request by martimavocado**
taken from the [neu repo](https://github.com/NotEnoughUpdates/NotEnoughUpdates-REPO/blob/master/constants/pets.json)

used in
- https://github.com/hannibal002/SkyHanni/pull/2605

### CODE REVIEW

**Comment by NopoTheGamer** [comment]
?

**Comment by martimavocado** [comment]
> ? whats wrong with the neu repo

nothing, i just think it makes more sense if the data is being used in skyhanni, for it to (also) be in the skyhanni repo.
also with a move to stop depending on NEU, i feel like it doesn't make a ton of sense to have the code look at the NEU repo, to then change it to looking at something else.
anyways i asked hanni about this yesterday, and didn't get a reply yet, if we have a better solution i'll just do that instead.

**Comment by NopoTheGamer** [comment]
you will still be using the neu repo even after neu lmao

**Comment by CalMWolfs** [comment]
> also with a move to stop depending on NEU, i feel like it doesn't make a ton of sense to have the code look at the NEU repo
This is only stopping depending on neu code, we will still use the neu-repo for items and other data like this. 
I dont forsee anytime in the future where we will not use the neu-repo, as if we did then we would have to keep 6000+ items up to date.

**Pull request closed without merging**
