### PR TITLE
Add special rabbits texture to HoppityEggLocations

### PR DESCRIPTION
**Pull request by superhize**

### CODE REVIEW

**Comment by CalMWolfs** [comment]
we could probably just put this stuff into the existing repo file

**Comment by superhize** [comment]
> we could probably just put this stuff into the existing repo file

Into the eggLocation file ?

**Comment by CalMWolfs** [comment]
> Into the eggLocation file ?

yeah, we have everything related to chocolate factory in there

**Review by jani270 — APPROVED** [review]
For sake of people testing the main pr, i will merge this early

**Pull request merged**
