### PR TITLE
Fixed trophy fish and made whole list lowercase

### PR DESCRIPTION
**Pull request by j10a1n15**

### CODE REVIEW

**Comment by hannibal002** [comment]
Why lower case? I liked the old design.
Do you think enchanted_cobblestone looks better than Enchanted_Cobblestone?

**Comment by j10a1n15** [comment]
I thought that that would fix the one word uppercase problem

**Comment by hannibal002** [comment]
I'm not entirely sure why it happened, my replacement change message was maybe causing an infinite loop, and it stopped at 2 iterations. Anyway, it's fixed in beta 20 already: https://github.com/hannibal002/SkyHanni/commit/21558b67f46538f86340a6bcf1e19a5081f7eb16

**Comment by j10a1n15** [comment]
Should I revert lowercase and keep the trophy fix?

**Comment by hannibal002** [comment]
Yes please.

**Pull request closed without merging**
