### PR TITLE
Add new salvageable items

### PR DESCRIPTION
**Pull request by lunaynx**
Added in SkyBlock 0.19.11.

### CODE REVIEW

**Review by CalMWolfs — CHANGES_REQUESTED** [review]
While you can salvage all of these I don't like having any of the treasure talismans or the scarf talismans in here as skyhannis not clickable items doubles as salvage protection. Which is the reason why weapons like spirit sceptre and giants sword aren't in this list.

**Comment by alexiayaa** [comment]
Makes sense I guess, Glacial Talisman can probably stay as you can get dupes of that quite easily, but the higher tiers perhaps not, especially since they give the same amount of Ice Essence as lower tiers. But it might be nice to differentiate "can't" and "shouldn't" be salvaged in the future.

**Comment by CalMWolfs** [comment]
> Makes sense I guess, Glacial Talisman can probably stay as you can get dupes of that quite easily, but the higher tiers perhaps not, especially since they give the same amount of Ice Essence as lower tiers. But it might be nice to differentiate "can't" and "shouldn't" be salvaged in the future.

Sounds good, yeah in future it could just say something different in the tooltip

**Review by hannibal002 — APPROVED** [review]
LGTM

**Pull request merged**
