### PR TITLE
roman number allow list

### PR DESCRIPTION
**Pull request by hannibal002**
adds a list of regex patterns that will be replaced by roman numeral replace feature

### CODE REVIEW

**Review by CalMWolfs — CHANGES_REQUESTED** [review]
we have repo pattern lists in the mod already, no point in new logic for this one thing

**Comment by hannibal002** [comment]
private val repoGroup = RepoPattern.group("inventory.pagescrolling")

    private val illegalInventory by repoGroup.list(
        "illegal",
        "Large Chest",
        "Chest",
    )

**Comment by hannibal002** [comment]
will do so soon

**Comment by hannibal002** [comment]
closing repo pattern lists are really easy to use. see https://github.com/hannibal002/SkyHanni/pull/3113/commits/4b0892ddf4e108030ea451998cdd67b6f5b45ab3

**Pull request closed without merging**
