### PR TITLE
Add enchants for Enchant Parsing

### PR DESCRIPTION
**Pull request by VixidDev**
Repo file for all enchants for Enchant Parsing (will make pr in mod soon). Includes the new ones SBA doesn't have

### CODE REVIEW

**Comment by jani270** [comment]
bruh

**Comment by VixidDev** [comment]
> bruh

why bruh?

**Comment by jani270** [comment]
Dont see why this is needed, we already have enchant colors in NEU, so good and max level is not needed.

**Comment by VixidDev** [comment]
> Dont see why this is needed, we already have enchant colors in NEU, so good and max level is not needed.

It's based on SBA's enchant parsing which colors them based on how good the level of the enchant is, which is different for man y enchants. With NEU you can only color them if they are above, below or equal to a level that matches a certain regex, i.e., 5 isn't max for Power but it is for Charm for example, with NEU you would end up having those be the same color, unless you manually recolor every enchant manually or try to group some with regex rules which is not really viable.

I and many others prefer SBA method of coloring the enchants. If hanni and others really don't want this feature and don't see the need then sure I guess I'll remove it. But I right now I see it as sufficiently different from NEU's one (and better IMO)

**Comment by jani270** [comment]
Or you can just download a preset, which already does that for you. This is just duping a feature and not making it better, but thats does not matter for this pr. I just dislike it really hard

**Comment by VixidDev** [comment]
Why go through the effort of finding a preset that probably has countless rules which someone may or may not have yet made. Then when you want to change a color of 1 or more enchants you have to scroll through to find them then change the color of each individually, and possibly the level of said enchant if Hypixel decide to add a new level to an enchant.

Whereas with this one you can just change the color of the max level enchants, great level enchants, good level enchants, and poor level enchants with relative ease. I wouldn't say its duping a feature, rather a (better) alternative. Also, seriously? You haven't seen one person that prefers SBA's one over NEU? Let me be the first I guess.

**Comment by jani270** [comment]
I think we should wait for hannibals opinion in this, for me its a FAR FAR worse alternative. Instead i would just add a button to neu to maxout enchants.

**Comment by hannibal002** [comment]
While i think it's true that most users only care for hyper maxed/super good /descent/bad enchantments color and ignoring ultimate enchants, i do like the endless possibilities of neu's custom settings. I don't know how useful a preset would be, since it feels a bit static when changes happen.

**Comment by Obsidianninja11** [comment]
Doesn't sba's enchant parsing change how the enchants are sorted or something too?
off


image

compress


normal


expand

**Comment by alexiayaa** [comment]
You should add Pesterminator btw, in case this ends up getting merged. I guess maybe good level can be like 3, I saw a lot of people with that. Max is 5.

**Comment by VixidDev** [comment]
> You should add Pesterminator btw, in case this ends up getting merged. I guess maybe good level can be like 3, I saw a lot of people with that. Max is 5.

Yeah, there have been a few enchants that have been added to the game since this PR, but I haven't been able to get around to it since I have been unbelievably busy with uni work, if I manage to find time in the next week I'll probably add the missing ones. Also thanks for the suggestion on the good level since I have no idea about any of the new enchants 😅.

> Sba's enchant parsing does more than just change enchant colors-

Correct, at the moment my enchant parsing forces compressed at the moment (3 enchants a line), the feature is not as exhaustive as sba's (yet). I've not been able to go over the code for my enchant parsing since I made the pull request, since as mentioned above, I have been extremely busy, and I wanted to re-write some of the code for it since I feel it could be improved a bit. With the exception of waiting until the missing enchants have been added to this PR, it should be (the PR on the main repo) in a state to be merged. I do plan to add the three options of formatting like in sba but don't have the time right now. (Also I think your comment may have been more relevant on the main repo than here)

**Review by hannibal002 — APPROVED** [review]

**Pull request merged**
